LandingPageProject/config/routes.rb
Rails.application.routes.draw do

  root 'homes#new'
  get "/landingpage2", to: 'home2#new' 

  resources :homes
  resources :mails

end

LandingPageProject/app/models/adress_mail.rb
class AdressMail < ApplicationRecord
end

LandingPageProject/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

LandingPageProject/app/models/user.rb
class User < ApplicationRecord



  #validates :first_name,  presence: true, length: { maximum: 50 }
  #validates :last_name,  presence: true, length: { maximum: 50 }
  #validates :city,  presence: true, length: { maximum: 50 }
  #validates :occupation,  presence: true, length: { maximum: 50 }
  #VALID_PHONE_REGEX = /\d{10}/mx
  #validates :phone,  presence: true, length: { minimum: 10, maximum: 10 },
  #					 format: { with: VALID_PHONE_REGEX }
 # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #validates :email, presence: true, length: { maximum: 50 },
  #                  format: { with: VALID_EMAIL_REGEX }



end

LandingPageProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

LandingPageProject/app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
	end

	def new
		@user = User.new
	end

	def create

		@hash = []
		puts params
		@first_name = params[:user][:first_name]
		@last_name = params[:user][:last_name]
		@email = params[:user][:email]
		@city = params[:user][:city]
		@phone = params[:user][:phone]
		@occupation = params[:user][:occupation]

		@hash = [@first_name, @last_name, @email, @city, @phone, @occupation]

		@user = User.create(first_name: @first_name, last_name:@last_name, email:@email, city: @city, phone:@phone, occupation:@occupation)
		
		UserMailer.new.welcome_mail(@email)



		File.open('db/info.json', 'w') do |f|
			f.write(@hash.to_json)

		end
	end


	def show
	end


end

LandingPageProject/app/controllers/mail_controller.rb
class MailController < ApplicationController
  def new
  	@mail = AdressMail.new
  end

  def create
  end

  def show
  end
end

LandingPageProject/app/helpers/application_helper.rb
module ApplicationHelper
end

LandingPageProject/app/helpers/home_helper.rb
module HomeHelper
end

LandingPageProject/app/helpers/mail_helper.rb
module MailHelper
end

LandingPageProject/app/views/home2/index.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>The Hacking Project</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->

    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Plugin CSS -->
    <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="css/freelancer.min.css" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondar fixed-top text-uppercase" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">The Hacking Project</a>
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primar text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio"></a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about"></a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact"></a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Header -->
    <header class="masthead bg-primar text-white text-center">
      <div class="container">
        <img class="img-fluid mb-5 d-block mx-auto" src="assets/thp.png" alt="">
        <h1 class="text-uppercase mb-0">The HackingProject</h1>
        <hr class=" mb-5" style="background-color: #fff; width:200px;">
        <h2 class="font-weight-light mb-0">Formation pour apprendre à coder autrement </h2>
      </div>
    </header>

    <!-- About Section -->
    <section class="bg-peer text-white mb-0" id="about">
      <div class="container">
        <h2 class="text-center text-uppercase text-white">Un travail de groupe</h2>
        <hr class=" mb-5" style="background-color: #fff; width:100px;">
        <div class="row">
          <div class="col-lg-4 ml-auto" style="padding-right:20px">
            <p class="lead">Pendant 12 semaines, vous allez vous retrouver tous les matins pour transpirer ensemble. Nous voulons que des polytechniciens apprennent à démarcher des restaurants avec des militaires en reconversion, des jeunes du 93, et des mères de famille.
            </p>
          </div>
          <br />
          <div class="col-lg-4 mr-auto" padding-left:20px">
            <p class="lead">Le but de toute cette communauté est de créér un écosystème bienveillant et où personne n'aura aucune gène à poser des questions, même les plus stupides. C'est en enseignant que l'on apprend, donc en quelque sorte la personne qui pose une question apprendra autant que la personne qui répond.</p>
          </div>
        </div>

      </div>
    </section>

    <!-- Contact Section -->
    <section id="contact">
      <div class="container">
        <h2 class="text-center text-uppercase text-secondar mb-0">Recevoir la newsletter</h2>
        <hr class="star-dark mb-5">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
            <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
            <form name="sentMessage" id="contactForm" novalidate="novalidate">
              <div class="control-group">
                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                  <label>First_name</label>
                  <input class="form-control" id="first_name" type="text" placeholder="First_name" required="required" data-validation-required-message="Please enter your first name.">
                  <p class="help-block text-danger"></p>
                </div>
              <div class="control-group">
                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                  <label>Last_name</label>
                  <input class="form-control" id="last_name" type="text" placeholder="Last_name" required="required" data-validation-required-message="Please enter your last name.">
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <div class="control-group">
                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                  <label>Email Address</label>
                  <input class="form-control" id="email" type="email" placeholder="Email Address" required="required" data-validation-required-message="Please enter your email address.">
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <div class="control-group">
                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                  <label>City</label>
                  <input class="form-control" id="city" type="text" placeholder="City" required="required" data-validation-required-message="Please enter your city.">
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <div class="control-group">
                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                  <label>Occupation</label>
                  <input class="form-control" id="occupation" type="text" placeholder="occupation" required="required" data-validation-required-message="Please enter your occupation."></textarea>
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <br>
              <div id="success"></div>
              <div class="form-group">
                <button type="submit" class="btn btn-xl" id="sendMessageButton">Send</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="footer text-center">
      <div class="container">
        <div class="row">
          <div class="col-md-4 mb-5 mb-lg-0">
            <h4 class="text-uppercase mb-4">Location</h4>
            <p class="lead mb-0">226, rue Saint-Denis
              <br>75002 Paris France</p>
          </div>
          <div class="col-md-4 mb-5 mb-lg-0">
            <h4 class="text-uppercase mb-4">Retrouvez-nous sur</h4>
            <ul class="list-inline mb-0">
              <li class="list-inline-item">
                <a href="https://www.facebook.com/thehackingproject/" alt="facebook">
                  <i class="fab fa-3x fa-facebook-square" style="width:50px;"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://mobile.twitter.com/the_hacking_pro" alt="twitter">
                  <i class="fab fa-3x fa-twitter-square"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.instagram.com/the_hacking_project/" alt="instagram">
                  <i class="fab fa-3x fa-instagram" style="width:50px;"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <h4 class="text-uppercase mb-4">Pour nous appeler</h4>
            <p>Charles Dacquay  06 95 46 60 80</p>
            <p>Félix Gaudé  06 28 01 33 40</p>

</html>

LandingPageProject/app/views/homes/create.html.erb
<h1>Homes#create</h1>
<p>Find me in app/views/homes/create.html.erb</p>

LandingPageProject/app/views/homes/new.html.erb
<div class="container-fluid">
  <div class="col-lg-12">
    <div class="row" id="back_img">
      <div class="col-md-8 offset-md-2">
        <div class="row" id="text">
          <div class="col-md-8 offset-md-2" id="titre">
            <a href="#contain2"><h1> The Hacking project</h1></a>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12" id="slogan">
            <h2>Formation pour apprendre à coder autrement</h2>
          </div>
        </div>
        <div class="row" id="description">
          <div class="col-lg-12">
            <h3>Formation gratuite durant 3 mois
            qui s'appuie sur une communauté soudée pour enseigner de manière innovante et pertinente.</h3>
          </div>
        </div>
      </div>
    </div>

    <div class="row" id="contain2">
      <div class="col-md-4 offset-md-4">

        <div class="jumbotron jumbotron-fluid">

          <h3>Recevoir la newletter</h3>
          <%= form_for(@user , url: homes_path) do |f| %>

          <div class="form-group row">
            <%= f.label :first_name  %>
            <%= f.text_field :first_name, placeholder: 'Your first name', class: 'form-control' %>
          </div>

          <div class="form-group row">
           <%= f.label :last_name %>
           <%= f.text_field :last_name, placeholder: 'Your last name', class: 'form-control' %>
         </div>

         <div class="form-group row">
           <%= f.label :email %>
           <%= f.email_field :email, placeholder: 'example@gmail.com', class: 'form-control' %>
         </div>

         <div class="form-group row">
           <%= f.label :city %>
           <%= f.text_field :city, placeholder: 'Your city', class: 'form-control' %>
         </div>

         <div class="form-group row">
          <%= f.label :occupation %>
          <%= f.text_field :occupation, placeholder: 'Your occupation', class: 'form-control' %>
        </div>


        <%= f.submit "Send", class: "btn btn-primary" %>

        <% end %>
      </div>
    </div>
  </div>
</div>

</div>

LandingPageProject/app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>